id: P4BD8ADCB
initial_creation_type: input
source_metadata:
  Title: Jñānaśrimitra’s Anupalabdhirahasya and Sarvaśabdābhāvacarcā
  Editor: '-'
  Publisher: Arbeitskreis Fur Tibetische Und Buddhistische Studien, Universitat Wien
  Place of Publication: Wien
  Year: '2007'
  सर्वशब्दभावचर्चा:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: May 2017
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:03:23.467115'
last_modified_at: '2022-03-08T17:03:23.467123'
